"""
app/seed.py

Generates realistic Sri Lankan dummy data for the hardware inventory system.

WHAT THIS DOES
--------------
- Runs only if the `categories` table is empty (anchor check) -> safe to
  restart the server repeatedly without duplicating or wiping edited data.
- Creates exactly ONE user: username "musfir", password "mustha" (bcrypt hashed
  via passlib, role=ADMIN).
- 25 hardware-related categories.
- 40 suppliers (7 inactive), Sri Lankan business names/addresses/phones.
- 150 items (22 inactive). ~60% of items with an open alert get restocked
  back above reorder_level by the end of their history; the rest are left
  genuinely low/out of stock right now, on purpose, so stock_alerts ends up
  with a realistic MIX of CRITICAL / LOW_STOCK / RESOLVED rows.
- ~1000 transactions, only for items that are active AND whose supplier is
  active. previous_quantity / new_quantity form a mathematically consistent
  chain per item (simulated forward, chronologically).
- StockAlert rows are generated by replaying the exact same state machine
  as your sync_stock_alert() service (CRITICAL/LOW_STOCK/RESOLVED
  transitions, single active alert per item, STOCK_OUT blocked while
  CRITICAL) - so alerts line up with the transaction history that caused
  them, not inserted independently.
- created_at is randomly scattered across the last 365 days for every table.
  updated_at == created_at everywhere (no edits have happened yet).
- Uses SQLAlchemy Core `insert()` with list-of-dicts (executemany), inserted
  in batches -> low memory, no per-row ORM object overhead.

REQUIREMENTS
------------
Uses the `bcrypt` package directly (already in your pyproject.toml).
passlib is NOT required by this script - it's skipped to avoid the known
passlib 1.7.4 vs bcrypt 4.1+ version-detection bug.

HOOK INTO FASTAPI STARTUP (app.py)
-----------------------------------
    from app.seed import seed_database

    @asynccontextmanager
    async def lifespan(_app: FastAPI):
        await create_db_and_tables()

        async with async_session_maker() as session:
            created = await AdminService.create_admin(session)
            ...

        await seed_database()   # <-- add this line

        yield
        await engine.dispose()

Adjust the `from app.models import ...` line below if your models file is
named differently.
"""

import random
import uuid
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from collections import defaultdict

import bcrypt
from sqlalchemy import select, insert, func

from app.database import async_session_maker
from app.models import (
    User,
    UserRole,
    Category,
    Supplier,
    Item,
    Transaction,
    TransactionType,
    StockAlert,
    AlertStatus,
)

# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #
local_tz = timezone(timedelta(hours=5, minutes=30))


def hash_password(plain: str) -> str:
    """Hash directly with bcrypt, bypassing passlib's broken version-detection
    self-test against bcrypt 4.1+. Produces a standard $2b$ bcrypt hash string
    identical to what passlib's bcrypt scheme would produce."""
    return bcrypt.hashpw(plain.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


NUM_CATEGORIES = 25
NUM_SUPPLIERS = 40
NUM_INACTIVE_SUPPLIERS = 7
NUM_ITEMS = 150
NUM_INACTIVE_ITEMS = 22
TARGET_TRANSACTIONS = 1000
BATCH_SIZE = 500

# --------------------------------------------------------------------------- #
# Sri Lankan name / address pools
# --------------------------------------------------------------------------- #
SINHALA_FIRST = [
    "Nimal",
    "Sunil",
    "Kamal",
    "Chaminda",
    "Ruwan",
    "Saman",
    "Priyantha",
    "Chandana",
    "Dilshan",
    "Lasantha",
    "Nuwan",
    "Roshan",
    "Tharindu",
    "Kasun",
    "Amila",
    "Nadeesha",
    "Chathurika",
    "Dilrukshi",
    "Kumari",
    "Malani",
    "Priyanka",
    "Sanduni",
    "Nayana",
    "Iresha",
    "Anusha",
]
SINHALA_LAST = [
    "Perera",
    "Fernando",
    "Silva",
    "Jayasuriya",
    "Wickramasinghe",
    "Gunasekara",
    "Rajapaksa",
    "Bandara",
    "Dissanayake",
    "Weerasinghe",
    "Karunaratne",
    "Mendis",
    "Rathnayake",
    "Senanayake",
    "Abeywickrama",
]
TAMIL_FIRST = [
    "Kumar",
    "Suresh",
    "Ravi",
    "Prasanna",
    "Vijay",
    "Anand",
    "Kishore",
    "Priya",
    "Kavitha",
    "Deepa",
    "Nirosha",
    "Thivya",
    "Vani",
    "Selvi",
]
TAMIL_LAST = [
    "Rajendran",
    "Kumaraswamy",
    "Sivakumar",
    "Muthulingam",
    "Sabaratnam",
    "Thiruchelvam",
    "Balasubramaniam",
    "Ganeshan",
    "Selvarajah",
]
MUSLIM_FIRST = [
    "Mohamed",
    "Ahamed",
    "Fathima",
    "Rizwan",
    "Nazeer",
    "Farhana",
    "Shafraz",
    "Rikaza",
    "Rushdie",
    "Ismail",
    "Nusrath",
    "Mansoor",
]
MUSLIM_LAST = [
    "Hameed",
    "Rasheed",
    "Careem",
    "Marikkar",
    "Naina",
    "Thaha",
    "Jayah",
    "Nizam",
    "Iqbal",
    "Rauf",
]

CITIES = [
    "Colombo",
    "Kandy",
    "Galle",
    "Negombo",
    "Jaffna",
    "Kurunegala",
    "Anuradhapura",
    "Batticaloa",
    "Trincomalee",
    "Matara",
    "Ratnapura",
    "Badulla",
    "Nuwara Eliya",
    "Gampaha",
    "Kalutara",
    "Puttalam",
    "Polonnaruwa",
    "Ampara",
    "Hambantota",
    "Kegalle",
]
STREET_NAMES = [
    "Main Street",
    "Temple Road",
    "Station Road",
    "Galle Road",
    "Kandy Road",
    "Negombo Road",
    "Hospital Road",
    "Lake Road",
    "Church Street",
    "Market Street",
    "Colombo Road",
    "Peradeniya Road",
]

SUPPLIER_NOTE_TEMPLATES = [
    "Reliable supplier with consistent delivery timelines.",
    "Preferred vendor for bulk orders.",
    "Offers discounts on orders above LKR 100000.",
    "Delivery within 3 to 5 working days island wide.",
    "Long term business partner since store opening.",
    "Occasional delays during peak season.",
    "Good quality control on delivered stock.",
    "Requires advance payment for new orders.",
]
SUPPLIER_SUFFIXES = [
    "Hardware Traders",
    "Hardware Suppliers",
    "Trading Company",
    "Enterprises",
    "Distributors",
    "Industries",
    "Building Materials",
    "Hardware Stores",
    "Trading House",
    "Suppliers",
]
SUPPLIER_PREFIXES = [
    "Ceylon",
    "Lanka",
    "National",
    "Metro",
    "Central",
    "Royal",
    "Sunrise",
    "Golden",
    "United",
    "Prime",
    "Coastal",
    "Highland",
    "Pearl",
    "Island",
    "Crown",
    "Premier",
]

# --------------------------------------------------------------------------- #
# Category catalog (hardware-related, letters/numbers/spaces only)
# --------------------------------------------------------------------------- #
CATEGORY_NAMES = [
    "Cement and Concrete",
    "Steel and Iron Rods",
    "Plumbing and Pipes",
    "Electrical Wiring",
    "Electrical Fittings",
    "Paints and Coatings",
    "Hand Tools",
    "Power Tools",
    "Fasteners and Screws",
    "Nails and Nuts Bolts",
    "Locks and Security",
    "Door and Window Hardware",
    "Roofing Sheets",
    "Tiles and Flooring",
    "Sanitary Ware",
    "Adhesives and Sealants",
    "Safety Equipment",
    "Garden and Outdoor Tools",
    "Ladders and Scaffolding",
    "Wood and Timber",
    "Glass and Mirrors",
    "Welding Equipment",
    "Water Tanks and Pumps",
    "Cleaning Supplies",
    "Measuring Instruments",
]
assert len(CATEGORY_NAMES) == NUM_CATEGORIES

# Each category -> (list of 3 product stems, list of sizes/variants, unit)
CATEGORY_ITEM_TEMPLATES = {
    "Cement and Concrete": (
        ["Portland Cement", "Rapid Set Cement", "Ready Mix Concrete"],
        ["25kg", "50kg", "Bag"],
        "Bags",
    ),
    "Steel and Iron Rods": (
        ["Deformed Steel Bar", "Round Iron Rod", "Steel Angle Bar"],
        ["8mm", "10mm", "12mm"],
        "Pieces",
    ),
    "Plumbing and Pipes": (
        ["PVC Pipe", "GI Pipe", "PPR Pipe"],
        ["1/2 inch", "3/4 inch", "1 inch"],
        "Pieces",
    ),
    "Electrical Wiring": (
        ["Copper Wire", "Flexible Cable", "Armoured Cable"],
        ["1.5mm", "2.5mm", "4mm"],
        "Meters",
    ),
    "Electrical Fittings": (
        ["Switch Socket", "MCB Breaker", "Ceiling Rose"],
        ["Single", "Double", "Standard"],
        "Pieces",
    ),
    "Paints and Coatings": (
        ["Emulsion Paint", "Enamel Paint", "Wood Varnish"],
        ["1L", "4L", "20L"],
        "Liters",
    ),
    "Hand Tools": (
        ["Claw Hammer", "Screwdriver Set", "Adjustable Wrench"],
        ["Small", "Medium", "Large"],
        "Pieces",
    ),
    "Power Tools": (
        ["Angle Grinder", "Electric Drill", "Circular Saw"],
        ["600W", "750W", "900W"],
        "Pieces",
    ),
    "Fasteners and Screws": (
        ["Wood Screw", "Machine Screw", "Self Tapping Screw"],
        ["1 inch", "2 inch", "3 inch"],
        "Box",
    ),
    "Nails and Nuts Bolts": (
        ["Common Nail", "Hex Bolt", "Wing Nut"],
        ["2 inch", "3 inch", "4 inch"],
        "Kg",
    ),
    "Locks and Security": (
        ["Door Lock Set", "Padlock", "Cylinder Lock"],
        ["Standard", "Heavy Duty", "Premium"],
        "Pieces",
    ),
    "Door and Window Hardware": (
        ["Door Hinge", "Window Handle", "Door Closer"],
        ["Small", "Medium", "Large"],
        "Pieces",
    ),
    "Roofing Sheets": (
        ["Asbestos Roofing Sheet", "Aluminium Roofing Sheet", "Colour Bond Sheet"],
        ["6ft", "8ft", "10ft"],
        "Sheets",
    ),
    "Tiles and Flooring": (
        ["Ceramic Floor Tile", "Wall Tile", "Vinyl Flooring"],
        ["300x300mm", "600x600mm", "Roll"],
        "Box",
    ),
    "Sanitary Ware": (
        ["Wash Basin", "Water Closet", "Bathroom Fitting Set"],
        ["Standard", "Premium", "Compact"],
        "Pieces",
    ),
    "Adhesives and Sealants": (
        ["Silicone Sealant", "Tile Adhesive", "Wood Glue"],
        ["300ml", "1kg", "5kg"],
        "Pieces",
    ),
    "Safety Equipment": (
        ["Safety Helmet", "Safety Gloves", "Safety Goggles"],
        ["Standard", "Heavy Duty", "Premium"],
        "Pieces",
    ),
    "Garden and Outdoor Tools": (
        ["Garden Spade", "Pruning Shears", "Garden Hose"],
        ["Standard", "Heavy Duty", "15m"],
        "Pieces",
    ),
    "Ladders and Scaffolding": (
        ["Aluminium Ladder", "Step Ladder", "Scaffold Pipe"],
        ["6ft", "8ft", "10ft"],
        "Pieces",
    ),
    "Wood and Timber": (
        ["Plywood Sheet", "Teak Timber Plank", "MDF Board"],
        ["4x8ft", "6ft", "8ft"],
        "Pieces",
    ),
    "Glass and Mirrors": (
        ["Clear Glass Sheet", "Bathroom Mirror", "Tempered Glass"],
        ["4mm", "5mm", "6mm"],
        "Pieces",
    ),
    "Welding Equipment": (
        ["Welding Rod", "Welding Mask", "Welding Machine"],
        ["Standard", "Heavy Duty", "Premium"],
        "Pieces",
    ),
    "Water Tanks and Pumps": (
        ["Water Storage Tank", "Submersible Pump", "Pressure Pump"],
        ["500L", "1000L", "Standard"],
        "Pieces",
    ),
    "Cleaning Supplies": (
        ["Industrial Broom", "Floor Cleaner", "Cleaning Cloth Pack"],
        ["Standard", "5L", "Pack of 10"],
        "Pieces",
    ),
    "Measuring Instruments": (
        ["Measuring Tape", "Spirit Level", "Digital Caliper"],
        ["5m", "600mm", "Standard"],
        "Pieces",
    ),
}


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def random_datetime_last_365_days() -> datetime:
    days_ago = random.randint(0, 365)
    seconds_in_day = random.randint(0, 86399)
    return datetime.now(local_tz) - timedelta(days=days_ago, seconds=seconds_in_day)


def gen_full_name() -> str:
    pool = random.choice(
        [
            (SINHALA_FIRST, SINHALA_LAST),
            (TAMIL_FIRST, TAMIL_LAST),
            (MUSLIM_FIRST, MUSLIM_LAST),
        ]
    )
    first, last = pool
    return f"{random.choice(first)} {random.choice(last)}"


def gen_phone(used: set) -> str:
    prefixes = ["070", "071", "072", "074", "075", "076", "077", "078"]
    while True:
        p = random.choice(prefixes)
        rest = f"{random.randint(0, 999):03d} {random.randint(0, 9999):04d}"
        phone = f"{p} {rest}"
        if phone not in used:
            used.add(phone)
            return phone


def gen_nic(used: set) -> str:
    while True:
        if random.random() < 0.5:
            nic = f"{random.randint(700000000, 999999999)}V"
        else:
            nic = f"{random.randint(199000000000, 200599999999)}"
        if nic not in used:
            used.add(nic)
            return nic


def gen_email(name: str, domain: str, used: set) -> str:
    base = name.lower().replace(" ", ".")
    email = f"{base}@{domain}"
    counter = 1
    while email in used:
        email = f"{base}{counter}@{domain}"
        counter += 1
    used.add(email)
    return email


def gen_address() -> str:
    return (
        f"No. {random.randint(1, 250)}, {random.choice(STREET_NAMES)}, "
        f"{random.choice(CITIES)}"
    )


def gen_supplier_name(used: set) -> str:
    while True:
        name = f"{random.choice(SUPPLIER_PREFIXES)} {random.choice(SUPPLIER_SUFFIXES)}"
        if name not in used:
            used.add(name)
            return name


def chunked(iterable, size):
    for i in range(0, len(iterable), size):
        yield iterable[i : i + size]


def simulate_item_history(
    item_id, supplier_id, reorder_level, count, user_id, resolve_probability=0.6
):
    """
    Forward-simulates a realistic transaction history for one item, replaying
    the EXACT same alert state machine as app/services sync_stock_alert():

      STOCK_OUT:
        - blocked entirely while an active alert is CRITICAL (stock == 0)
        - new_stock == 0            -> CRITICAL
        - 0 < new_stock < reorder   -> LOW_STOCK
        - new_stock >= reorder      -> no alert change
        - if an alert is already active, its status is UPDATED in place
          (same row) rather than a new alert being created

      STOCK_IN:
        - no active alert -> no alert change (stays healthy)
        - active alert, new_stock >= reorder -> RESOLVED (resolved_at set,
          alert closes)
        - active alert, new_stock < reorder  -> stays open as LOW_STOCK

    Returns (final_quantity_in_stock, transaction_rows, alert_rows).

    If the item still has an open alert after its random history plays out,
    it is force-resolved with probability `resolve_probability` (one final
    STOCK_IN "restock" transaction), so its current stock ends up healthy.
    Otherwise the alert is left genuinely open (CRITICAL or LOW_STOCK) and
    the item's current stock stays low/zero - this is what gives you a
    realistic MIX of CRITICAL / LOW_STOCK / RESOLVED rows in stock_alerts
    at once, matching a real point-in-time snapshot of the store.
    """
    starting_stock = reorder_level + random.randint(50, 150)

    if count == 0:
        return starting_stock, [], []

    dates = sorted(random_datetime_last_365_days() for _ in range(count))

    current_stock = starting_stock
    active_alert = None  # dict, mutated in place to mimic "same row updated"
    transaction_rows = []
    alert_rows = []

    for date in dates:
        # Mirrors: "if active and active.status == CRITICAL: raise 400"
        # i.e. a STOCK_OUT is impossible while at zero stock - only
        # restocking (STOCK_IN) can happen next.
        if active_alert and active_alert["status"] == AlertStatus.CRITICAL:
            t_type = TransactionType.STOCK_IN
        else:
            t_type = random.choices(
                [TransactionType.STOCK_OUT, TransactionType.STOCK_IN],
                weights=[65, 35],
            )[0]

        prev_stock = current_stock

        if t_type == TransactionType.STOCK_OUT:
            max_out = min(current_stock, 50)
            if max_out < 1:
                t_type = TransactionType.STOCK_IN
                qty = random.randint(5, 100)
                new_stock = current_stock + qty
            else:
                qty = random.randint(1, max_out)
                new_stock = current_stock - qty
        else:
            qty = random.randint(5, 100)
            new_stock = current_stock + qty

        current_stock = new_stock

        # ---- Replay sync_stock_alert()'s exact branching ---- #
        if t_type == TransactionType.STOCK_OUT:
            if new_stock == 0:
                target = AlertStatus.CRITICAL
            elif new_stock < reorder_level:
                target = AlertStatus.LOW_STOCK
            else:
                target = None

            if target is not None:
                if active_alert:
                    active_alert["status"] = target
                else:
                    active_alert = {
                        "alert_id": uuid.uuid4(),
                        "item_id": item_id,
                        "supplier_id": supplier_id,
                        "status": target,
                        "created_at": date,
                        "resolved_at": None,
                    }
                    alert_rows.append(active_alert)
        else:  # STOCK_IN
            if active_alert:
                if new_stock >= reorder_level:
                    active_alert["status"] = AlertStatus.RESOLVED
                    active_alert["resolved_at"] = date
                    active_alert = None
                else:
                    active_alert["status"] = AlertStatus.LOW_STOCK

        note = (
            "Stock received from supplier"
            if t_type == TransactionType.STOCK_IN
            else "Stock issued to customer"
        )
        transaction_rows.append(
            dict(
                transaction_id=uuid.uuid4(),
                item_id=item_id,
                user_id=user_id,
                transaction_type=t_type,
                quantity=qty,
                previous_quantity=prev_stock,
                new_quantity=new_stock,
                transaction_date=date,
                note=note,
            )
        )

    # With probability resolve_probability, force-resolve any still-open
    # alert (restocked -> current stock healthy). Otherwise, leave it open
    # so the item is genuinely CRITICAL/LOW_STOCK right now - this is what
    # produces a realistic mix across stock_alerts instead of everything
    # ending up RESOLVED.
    if active_alert and random.random() < resolve_probability:
        last_date = dates[-1]
        resolve_date = min(
            last_date + timedelta(hours=random.randint(1, 48)),
            datetime.now(local_tz),
        )
        if resolve_date <= last_date:
            resolve_date = last_date + timedelta(minutes=1)

        qty = max(reorder_level - current_stock, 0) + random.randint(20, 100)
        new_stock = current_stock + qty

        transaction_rows.append(
            dict(
                transaction_id=uuid.uuid4(),
                item_id=item_id,
                user_id=user_id,
                transaction_type=TransactionType.STOCK_IN,
                quantity=qty,
                previous_quantity=current_stock,
                new_quantity=new_stock,
                transaction_date=resolve_date,
                note="Stock received from supplier - restock",
            )
        )

        active_alert["status"] = AlertStatus.RESOLVED
        active_alert["resolved_at"] = resolve_date
        current_stock = new_stock

    return current_stock, transaction_rows, alert_rows


# --------------------------------------------------------------------------- #
# Main seeding routine
# --------------------------------------------------------------------------- #
async def seed_database() -> None:
    async with async_session_maker() as session:

        # ---- Anchor check: only seed if categories table is empty ---- #
        result = await session.execute(select(func.count()).select_from(Category))
        category_count: int = result.scalar_one()
        if category_count > 0:
            print("Seed data already present - skipping seeding.")
            return

        used_phones: set = set()
        used_nics: set = set()
        used_emails: set = set()
        used_supplier_names: set = set()

        # ------------------------------------------------------------- #
        # 1. musfir user (the ONLY user this script creates)
        #    Checked independently of the categories anchor - if someone
        #    only truncates categories (not users) and restarts, this
        #    won't crash on a duplicate; it reuses the existing user_id.
        # ------------------------------------------------------------- #
        existing_user = await session.execute(
            select(User.user_id).where(User.user_name == "musfir")
        )
        existing_user_id = existing_user.scalar_one_or_none()

        if existing_user_id is not None:
            musfir_id = existing_user_id
            print("musfir user already exists - reusing it.")
        else:
            musfir_id = uuid.uuid4()
            ts = random_datetime_last_365_days()
            await session.execute(
                insert(User).values(
                    user_id=musfir_id,
                    full_name="Musfir Mohamed",
                    user_name="musfir",
                    nic=gen_nic(used_nics),
                    email=gen_email("musfir", "lankahardware.lk", used_emails),
                    phone=gen_phone(used_phones),
                    password_hash=hash_password("mustha"),
                    role=UserRole.ADMIN,
                    is_active=True,
                    created_at=ts,
                    updated_at=ts,
                )
            )

        # ------------------------------------------------------------- #
        # 2. Categories
        # ------------------------------------------------------------- #
        category_rows = []
        category_ids = []
        for name in CATEGORY_NAMES:
            cid = uuid.uuid4()
            category_ids.append((cid, name))
            ts = random_datetime_last_365_days()
            category_rows.append(
                dict(
                    category_id=cid,
                    category_name=name,
                    description=f"Products and supplies related to {name.lower()}.",
                    created_at=ts,
                    updated_at=ts,
                )
            )
        await session.execute(insert(Category), category_rows)

        # ------------------------------------------------------------- #
        # 3. Suppliers (40 total, 7 inactive)
        # ------------------------------------------------------------- #
        inactive_flags = [False] * (NUM_SUPPLIERS - NUM_INACTIVE_SUPPLIERS) + [
            True
        ] * NUM_INACTIVE_SUPPLIERS
        random.shuffle(inactive_flags)

        supplier_rows = []
        suppliers = []  # (supplier_id, is_active)
        for i in range(NUM_SUPPLIERS):
            sid = uuid.uuid4()
            is_inactive = inactive_flags[i]
            ts = random_datetime_last_365_days()
            supplier_rows.append(
                dict(
                    supplier_id=sid,
                    supplier_name=gen_supplier_name(used_supplier_names),
                    contact_person=gen_full_name(),
                    phone=gen_phone(used_phones),
                    email=gen_email(f"supplier{i+1}", "suppliers.lk", used_emails),
                    address=gen_address(),
                    is_active=not is_inactive,
                    created_at=ts,
                    updated_at=ts,
                    notes=random.choice(SUPPLIER_NOTE_TEMPLATES),
                    total_supplies=random.randint(5, 200),
                )
            )
            suppliers.append((sid, not is_inactive))
        await session.execute(insert(Supplier), supplier_rows)

        # ------------------------------------------------------------- #
        # 4. Items (150 total, 22 inactive, always above reorder level)
        #    quantity_in_stock is decided AFTER simulating each item's
        #    transaction + alert history below (step 5), not here.
        # ------------------------------------------------------------- #
        inactive_item_flags = [False] * (NUM_ITEMS - NUM_INACTIVE_ITEMS) + [
            True
        ] * NUM_INACTIVE_ITEMS
        random.shuffle(inactive_item_flags)

        item_base = []  # metadata only, quantity_in_stock filled in later
        used_item_names: set = set()
        sku_counter = 1000

        # Build 6 unique items per category (25 x 6 = 150)
        idx = 0
        for cid, cname in category_ids:
            stems, sizes, unit = CATEGORY_ITEM_TEMPLATES[cname]
            combos = [(s, sz) for s in stems for sz in sizes]  # 3 x 3 = 9 combos
            random.shuffle(combos)
            chosen_combos = combos[:6]

            prefix = "".join(w[0] for w in cname.split() if w.lower() != "and").upper()

            for stem, size in chosen_combos:
                item_id = uuid.uuid4()
                item_name = f"{stem} {size}"
                if item_name in used_item_names:
                    item_name = f"{item_name} {random.randint(1, 999)}"
                used_item_names.add(item_name)

                sku_counter += 1
                sku = f"{prefix}-{sku_counter}"

                supplier_id, supplier_active = random.choice(suppliers)
                is_active = not inactive_item_flags[idx]

                reorder_level = random.randint(10, 50)

                cost_price = (
                    Decimal(random.randint(150, 15000)) / 100 * random.randint(1, 20)
                )
                cost_price = Decimal(str(round(float(cost_price), 2)))
                selling_price = Decimal(
                    str(round(float(cost_price) * random.uniform(1.15, 1.6), 2))
                )

                ts = random_datetime_last_365_days()
                item_base.append(
                    dict(
                        item_id=item_id,
                        item_name=item_name,
                        sku=sku,
                        description=f"{item_name} - suitable for residential and commercial use.",
                        category_id=cid,
                        supplier_id=supplier_id,
                        unit=unit,
                        cost_price=cost_price,
                        selling_price=selling_price,
                        reorder_level=reorder_level,
                        reorder_quantity=random.randint(20, 100),
                        is_active=is_active,
                        supplier_active=supplier_active,
                        created_at=ts,
                        updated_at=ts,
                    )
                )
                idx += 1

        # ------------------------------------------------------------- #
        # 5. Simulate transaction + alert history per item (~1000 total
        #    transactions), only for items that are active AND whose
        #    supplier is active. Alerts are created/resolved by replaying
        #    the same state machine as sync_stock_alert().
        # ------------------------------------------------------------- #
        eligible = [m for m in item_base if m["is_active"] and m["supplier_active"]]

        counts_per_item = defaultdict(int)
        for _ in range(TARGET_TRANSACTIONS):
            meta = random.choice(eligible)
            counts_per_item[meta["item_id"]] += 1

        item_rows = []
        transaction_rows = []
        alert_rows = []

        for meta in item_base:
            count = counts_per_item.get(meta["item_id"], 0)
            final_qty, tx_rows, alerts = simulate_item_history(
                item_id=meta["item_id"],
                supplier_id=meta["supplier_id"],
                reorder_level=meta["reorder_level"],
                count=count,
                user_id=musfir_id,
            )
            transaction_rows.extend(tx_rows)
            alert_rows.extend(alerts)

            item_rows.append(
                dict(
                    item_id=meta["item_id"],
                    item_name=meta["item_name"],
                    sku=meta["sku"],
                    description=meta["description"],
                    category_id=meta["category_id"],
                    supplier_id=meta["supplier_id"],
                    quantity_in_stock=final_qty,
                    unit=meta["unit"],
                    cost_price=meta["cost_price"],
                    selling_price=meta["selling_price"],
                    reorder_level=meta["reorder_level"],
                    reorder_quantity=meta["reorder_quantity"],
                    is_active=meta["is_active"],
                    created_at=meta["created_at"],
                    updated_at=meta["updated_at"],
                )
            )

        await session.execute(insert(Item), item_rows)

        if alert_rows:
            for batch in chunked(alert_rows, BATCH_SIZE):
                await session.execute(insert(StockAlert), batch)

        for batch in chunked(transaction_rows, BATCH_SIZE):
            await session.execute(insert(Transaction), batch)

        await session.commit()

        critical_count = sum(
            1 for a in alert_rows if a["status"] == AlertStatus.CRITICAL
        )
        low_stock_count = sum(
            1 for a in alert_rows if a["status"] == AlertStatus.LOW_STOCK
        )
        resolved_count = sum(
            1 for a in alert_rows if a["status"] == AlertStatus.RESOLVED
        )
        print(
            f"Seed complete: 1 user, {len(category_rows)} categories, "
            f"{len(supplier_rows)} suppliers, {len(item_rows)} items, "
            f"{len(transaction_rows)} transactions, {len(alert_rows)} alerts "
            f"({critical_count} critical, {low_stock_count} low stock, "
            f"{resolved_count} resolved)."
        )


if __name__ == "__main__":
    import asyncio

    asyncio.run(seed_database())
