"""
app/seed.py

Generates realistic Sri Lankan dummy data for the hardware inventory system.

WHAT THIS DOES
--------------
- Runs only if the `categories` table is empty (anchor check) -> safe to
  restart the server repeatedly without duplicating or wiping edited data.
- Creates exactly ONE user: username "musfir", password "mustha" (bcrypt hashed
  via passlib, role=ADMIN).
- 25 hardware-related categories.
- 40 suppliers (7 inactive), Sri Lankan business names/addresses/phones.
- 150 items (22 inactive). ~60% of items with an open alert get restocked
  back above reorder_level by the end of their history; the rest are left
  genuinely low/out of stock right now, on purpose, so stock_alerts ends up
  with a realistic MIX of CRITICAL / LOW_STOCK / RESOLVED rows.
- ~1000 transactions, only for items that are active AND whose supplier is
  active. previous_quantity / new_quantity form a mathematically consistent
  chain per item (simulated forward, chronologically).
- StockAlert rows are generated by replaying the exact same state machine
  as your sync_stock_alert() service (CRITICAL/LOW_STOCK/RESOLVED
  transitions, single active alert per item, STOCK_OUT blocked while
  CRITICAL) - so alerts line up with the transaction history that caused
  them, not inserted independently.
- created_at is randomly scattered across the last 365 days for every table.
  updated_at == created_at everywhere (no edits have happened yet).
- Uses SQLAlchemy Core `insert()` with list-of-dicts (executemany), inserted
  in batches -> low memory, no per-row ORM object overhead.

REQUIREMENTS
------------
Uses the `bcrypt` package directly (already in your pyproject.toml).
passlib is NOT required by this script - it's skipped to avoid the known
passlib 1.7.4 vs bcrypt 4.1+ version-detection bug.

HOOK INTO FASTAPI STARTUP (app.py)
-----------------------------------
    from app.seed import seed_database

    @asynccontextmanager
    async def lifespan(_app: FastAPI):
        await create_db_and_tables()

        async with async_session_maker() as session:
            created = await AdminService.create_admin(session)
            ...

        await seed_database()   # <-- add this line

        yield
        await engine.dispose()

Adjust the `from app.models import ...` line below if your models file is
named differently.
"""

import random
import uuid
from datetime import datetime, timedelta
from decimal import Decimal
from collections import defaultdict

import bcrypt
from sqlalchemy import select, insert, func

from app.database import async_session_maker
from app.models import (
    User,
    UserRole,
    Category,
    Supplier,
    Item,
    Transaction,
    TransactionType,
    StockAlert,
    AlertStatus,
    AuditLog,
    AuditAction,
)

# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #
local_tz = datetime.now().astimezone().tzinfo


def hash_password(plain: str) -> str:
    """Hash directly with bcrypt, bypassing passlib's broken version-detection
    self-test against bcrypt 4.1+. Produces a standard $2b$ bcrypt hash string
    identical to what passlib's bcrypt scheme would produce."""
    return bcrypt.hashpw(plain.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


NUM_CATEGORIES = 25
NUM_SUPPLIERS = 40
NUM_INACTIVE_SUPPLIERS = 7
NUM_ITEMS = 150
NUM_INACTIVE_ITEMS = 22
TARGET_TRANSACTIONS = 1000
BATCH_SIZE = 500
DEFAULT_PASSWORD = "Password@123"  # used for all seeded users except musfir

# --------------------------------------------------------------------------- #
# Sri Lankan name / address pools
# --------------------------------------------------------------------------- #
SINHALA_FIRST = [
    "Nimal",
    "Sunil",
    "Kamal",
    "Chaminda",
    "Ruwan",
    "Saman",
    "Priyantha",
    "Chandana",
    "Dilshan",
    "Lasantha",
    "Nuwan",
    "Roshan",
    "Tharindu",
    "Kasun",
    "Amila",
    "Nadeesha",
    "Chathurika",
    "Dilrukshi",
    "Kumari",
    "Malani",
    "Priyanka",
    "Sanduni",
    "Nayana",
    "Iresha",
    "Anusha",
]
SINHALA_LAST = [
    "Perera",
    "Fernando",
    "Silva",
    "Jayasuriya",
    "Wickramasinghe",
    "Gunasekara",
    "Rajapaksa",
    "Bandara",
    "Dissanayake",
    "Weerasinghe",
    "Karunaratne",
    "Mendis",
    "Rathnayake",
    "Senanayake",
    "Abeywickrama",
]
TAMIL_FIRST = [
    "Kumar",
    "Suresh",
    "Ravi",
    "Prasanna",
    "Vijay",
    "Anand",
    "Kishore",
    "Priya",
    "Kavitha",
    "Deepa",
    "Nirosha",
    "Thivya",
    "Vani",
    "Selvi",
]
TAMIL_LAST = [
    "Rajendran",
    "Kumaraswamy",
    "Sivakumar",
    "Muthulingam",
    "Sabaratnam",
    "Thiruchelvam",
    "Balasubramaniam",
    "Ganeshan",
    "Selvarajah",
]
MUSLIM_FIRST = [
    "Mohamed",
    "Ahamed",
    "Fathima",
    "Rizwan",
    "Nazeer",
    "Farhana",
    "Shafraz",
    "Rikaza",
    "Rushdie",
    "Ismail",
    "Nusrath",
    "Mansoor",
]
MUSLIM_LAST = [
    "Hameed",
    "Rasheed",
    "Careem",
    "Marikkar",
    "Naina",
    "Thaha",
    "Jayah",
    "Nizam",
    "Iqbal",
    "Rauf",
]

CITIES = [
    "Colombo",
    "Kandy",
    "Galle",
    "Negombo",
    "Jaffna",
    "Kurunegala",
    "Anuradhapura",
    "Batticaloa",
    "Trincomalee",
    "Matara",
    "Ratnapura",
    "Badulla",
    "Nuwara Eliya",
    "Gampaha",
    "Kalutara",
    "Puttalam",
    "Polonnaruwa",
    "Ampara",
    "Hambantota",
    "Kegalle",
]
STREET_NAMES = [
    "Main Street",
    "Temple Road",
    "Station Road",
    "Galle Road",
    "Kandy Road",
    "Negombo Road",
    "Hospital Road",
    "Lake Road",
    "Church Street",
    "Market Street",
    "Colombo Road",
    "Peradeniya Road",
]

SUPPLIER_NOTE_TEMPLATES = [
    "Reliable supplier with consistent delivery timelines.",
    "Preferred vendor for bulk orders.",
    "Offers discounts on orders above LKR 100000.",
    "Delivery within 3 to 5 working days island wide.",
    "Long term business partner since store opening.",
    "Occasional delays during peak season.",
    "Good quality control on delivered stock.",
    "Requires advance payment for new orders.",
]
SUPPLIER_SUFFIXES = [
    "Hardware Traders",
    "Hardware Suppliers",
    "Trading Company",
    "Enterprises",
    "Distributors",
    "Industries",
    "Building Materials",
    "Hardware Stores",
    "Trading House",
    "Suppliers",
]
SUPPLIER_PREFIXES = [
    "Ceylon",
    "Lanka",
    "National",
    "Metro",
    "Central",
    "Royal",
    "Sunrise",
    "Golden",
    "United",
    "Prime",
    "Coastal",
    "Highland",
    "Pearl",
    "Island",
    "Crown",
    "Premier",
]

# --------------------------------------------------------------------------- #
# Category catalog (hardware-related, letters/numbers/spaces only)
# --------------------------------------------------------------------------- #
CATEGORY_NAMES = [
    "Cement and Concrete",
    "Steel and Iron Rods",
    "Plumbing and Pipes",
    "Electrical Wiring",
    "Electrical Fittings",
    "Paints and Coatings",
    "Hand Tools",
    "Power Tools",
    "Fasteners and Screws",
    "Nails and Nuts Bolts",
    "Locks and Security",
    "Door and Window Hardware",
    "Roofing Sheets",
    "Tiles and Flooring",
    "Sanitary Ware",
    "Adhesives and Sealants",
    "Safety Equipment",
    "Garden and Outdoor Tools",
    "Ladders and Scaffolding",
    "Wood and Timber",
    "Glass and Mirrors",
    "Welding Equipment",
    "Water Tanks and Pumps",
    "Cleaning Supplies",
    "Measuring Instruments",
]
assert len(CATEGORY_NAMES) == NUM_CATEGORIES

# Each category -> (list of 3 product stems, list of sizes/variants, unit)
CATEGORY_ITEM_TEMPLATES = {
    "Cement and Concrete": (
        ["Portland Cement", "Rapid Set Cement", "Ready Mix Concrete"],
        ["25kg", "50kg", "Bag"],
        "Bags",
    ),
    "Steel and Iron Rods": (
        ["Deformed Steel Bar", "Round Iron Rod", "Steel Angle Bar"],
        ["8mm", "10mm", "12mm"],
        "Pieces",
    ),
    "Plumbing and Pipes": (
        ["PVC Pipe", "GI Pipe", "PPR Pipe"],
        ["1/2 inch", "3/4 inch", "1 inch"],
        "Pieces",
    ),
    "Electrical Wiring": (
        ["Copper Wire", "Flexible Cable", "Armoured Cable"],
        ["1.5mm", "2.5mm", "4mm"],
        "Meters",
    ),
    "Electrical Fittings": (
        ["Switch Socket", "MCB Breaker", "Ceiling Rose"],
        ["Single", "Double", "Standard"],
        "Pieces",
    ),
    "Paints and Coatings": (
        ["Emulsion Paint", "Enamel Paint", "Wood Varnish"],
        ["1L", "4L", "20L"],
        "Liters",
    ),
    "Hand Tools": (
        ["Claw Hammer", "Screwdriver Set", "Adjustable Wrench"],
        ["Small", "Medium", "Large"],
        "Pieces",
    ),
    "Power Tools": (
        ["Angle Grinder", "Electric Drill", "Circular Saw"],
        ["600W", "750W", "900W"],
        "Pieces",
    ),
    "Fasteners and Screws": (
        ["Wood Screw", "Machine Screw", "Self Tapping Screw"],
        ["1 inch", "2 inch", "3 inch"],
        "Box",
    ),
    "Nails and Nuts Bolts": (
        ["Common Nail", "Hex Bolt", "Wing Nut"],
        ["2 inch", "3 inch", "4 inch"],
        "Kg",
    ),
    "Locks and Security": (
        ["Door Lock Set", "Padlock", "Cylinder Lock"],
        ["Standard", "Heavy Duty", "Premium"],
        "Pieces",
    ),
    "Door and Window Hardware": (
        ["Door Hinge", "Window Handle", "Door Closer"],
        ["Small", "Medium", "Large"],
        "Pieces",
    ),
    "Roofing Sheets": (
        ["Asbestos Roofing Sheet", "Aluminium Roofing Sheet", "Colour Bond Sheet"],
        ["6ft", "8ft", "10ft"],
        "Sheets",
    ),
    "Tiles and Flooring": (
        ["Ceramic Floor Tile", "Wall Tile", "Vinyl Flooring"],
        ["300x300mm", "600x600mm", "Roll"],
        "Box",
    ),
    "Sanitary Ware": (
        ["Wash Basin", "Water Closet", "Bathroom Fitting Set"],
        ["Standard", "Premium", "Compact"],
        "Pieces",
    ),
    "Adhesives and Sealants": (
        ["Silicone Sealant", "Tile Adhesive", "Wood Glue"],
        ["300ml", "1kg", "5kg"],
        "Pieces",
    ),
    "Safety Equipment": (
        ["Safety Helmet", "Safety Gloves", "Safety Goggles"],
        ["Standard", "Heavy Duty", "Premium"],
        "Pieces",
    ),
    "Garden and Outdoor Tools": (
        ["Garden Spade", "Pruning Shears", "Garden Hose"],
        ["Standard", "Heavy Duty", "15m"],
        "Pieces",
    ),
    "Ladders and Scaffolding": (
        ["Aluminium Ladder", "Step Ladder", "Scaffold Pipe"],
        ["6ft", "8ft", "10ft"],
        "Pieces",
    ),
    "Wood and Timber": (
        ["Plywood Sheet", "Teak Timber Plank", "MDF Board"],
        ["4x8ft", "6ft", "8ft"],
        "Pieces",
    ),
    "Glass and Mirrors": (
        ["Clear Glass Sheet", "Bathroom Mirror", "Tempered Glass"],
        ["4mm", "5mm", "6mm"],
        "Pieces",
    ),
    "Welding Equipment": (
        ["Welding Rod", "Welding Mask", "Welding Machine"],
        ["Standard", "Heavy Duty", "Premium"],
        "Pieces",
    ),
    "Water Tanks and Pumps": (
        ["Water Storage Tank", "Submersible Pump", "Pressure Pump"],
        ["500L", "1000L", "Standard"],
        "Pieces",
    ),
    "Cleaning Supplies": (
        ["Industrial Broom", "Floor Cleaner", "Cleaning Cloth Pack"],
        ["Standard", "5L", "Pack of 10"],
        "Pieces",
    ),
    "Measuring Instruments": (
        ["Measuring Tape", "Spirit Level", "Digital Caliper"],
        ["5m", "600mm", "Standard"],
        "Pieces",
    ),
}


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def random_datetime_last_365_days() -> datetime:
    days_ago = random.randint(0, 365)
    seconds_in_day = random.randint(0, 86399)
    return datetime.now(local_tz) - timedelta(days=days_ago, seconds=seconds_in_day)


def gen_full_name() -> str:
    pool = random.choice(
        [
            (SINHALA_FIRST, SINHALA_LAST),
            (TAMIL_FIRST, TAMIL_LAST),
            (MUSLIM_FIRST, MUSLIM_LAST),
        ]
    )
    first, last = pool
    return f"{random.choice(first)} {random.choice(last)}"


def gen_phone(used: set) -> str:
    prefixes = ["070", "071", "072", "074", "075", "076", "077", "078"]
    while True:
        p = random.choice(prefixes)
        rest = f"{random.randint(0, 999):03d} {random.randint(0, 9999):04d}"
        phone = f"{p} {rest}"
        if phone not in used:
            used.add(phone)
            return phone


def gen_nic(used: set) -> str:
    while True:
        if random.random() < 0.5:
            nic = f"{random.randint(700000000, 999999999)}V"
        else:
            nic = f"{random.randint(199000000000, 200599999999)}"
        if nic not in used:
            used.add(nic)
            return nic


def gen_email(name: str, domain: str, used: set) -> str:
    base = name.lower().replace(" ", ".")
    email = f"{base}@{domain}"
    counter = 1
    while email in used:
        email = f"{base}{counter}@{domain}"
        counter += 1
    used.add(email)
    return email


def gen_address() -> str:
    return (
        f"No. {random.randint(1, 250)}, {random.choice(STREET_NAMES)}, "
        f"{random.choice(CITIES)}"
    )


def gen_supplier_name(used: set) -> str:
    while True:
        name = f"{random.choice(SUPPLIER_PREFIXES)} {random.choice(SUPPLIER_SUFFIXES)}"
        if name not in used:
            used.add(name)
            return name


def gen_username(full_name: str, used: set) -> str:
    base = full_name.lower().replace(" ", ".")
    base = "".join(ch for ch in base if ch.isalnum() or ch in "._")
    username = base
    counter = 1
    while username in used:
        username = f"{base}{counter}"
        counter += 1
    used.add(username)
    return username


def pick_admin_or_im_creator(admin_ids, im_ids):
    """Creator pool = the 2 admins + 1 inventory manager (randomly chosen
    per call from the available IMs) - matches 'created by 2 admins and
    1 IM' for category/supplier/item creation audit logs."""
    pool = list(admin_ids)
    if im_ids:
        pool.append(random.choice(im_ids))
    return random.choice(pool)


def chunked(iterable, size):
    for i in range(0, len(iterable), size):
        yield iterable[i : i + size]


def simulate_item_history(
    item_id, supplier_id, reorder_level, count, transaction_user_ids
):
    """
    Forward-simulates a realistic transaction history for one item, replaying
    the EXACT same alert state machine as app/services sync_stock_alert():

      STOCK_OUT:
        - blocked entirely while an active alert is CRITICAL (stock == 0)
        - new_stock == 0            -> CRITICAL
        - 0 < new_stock < reorder   -> LOW_STOCK
        - new_stock >= reorder      -> no alert change
        - if an alert is already active, its status is UPDATED in place
          (same row) rather than a new alert being created

      STOCK_IN:
        - no active alert -> no alert change (stays healthy)
        - active alert, new_stock >= reorder -> RESOLVED (resolved_at set,
          alert closes)
        - active alert, new_stock < reorder  -> stays open as LOW_STOCK

    Every transaction's user_id is drawn randomly from `transaction_user_ids`
    (only ADMIN/INVENTORY_MANAGER users, per business rule - SALES/AUDITOR
    never perform stock transactions).

    Any alert still open at the end of this item's random history is ALWAYS
    force-resolved here (one final restock transaction), so this function
    never leaves an item unhealthy. The handful of items that should stay
    genuinely CRITICAL/LOW_STOCK "as of now" are handled separately, on top
    of this, by the caller - see craft_terminal_alert() below.

    Returns (final_quantity_in_stock, transaction_rows, alert_rows, last_date).
    `last_date` is None if this item had zero transactions.
    """
    starting_stock = reorder_level + random.randint(50, 150)

    if count == 0:
        return starting_stock, [], [], None

    dates = sorted(random_datetime_last_365_days() for _ in range(count))

    current_stock = starting_stock
    active_alert = None  # dict, mutated in place to mimic "same row updated"
    transaction_rows = []
    alert_rows = []

    # Keep baseline STOCK_OUT quantities smaller within the last 30 days so
    # this random history doesn't accidentally overshoot the ~1,000,000
    # monthly sold-value target on its own - the dedicated top-up step
    # (5c in seed_database) then tops it up precisely. Trimming after the
    # fact isn't an option since that would break the previous/new
    # quantity chain.
    recent_cutoff = datetime.now(local_tz) - timedelta(days=30)

    for date in dates:
        # Mirrors: "if active and active.status == CRITICAL: raise 400"
        # i.e. a STOCK_OUT is impossible while at zero stock - only
        # restocking (STOCK_IN) can happen next.
        is_recent = date >= recent_cutoff
        if active_alert and active_alert["status"] == AlertStatus.CRITICAL:
            t_type = TransactionType.STOCK_IN
        else:
            # Bias harder toward STOCK_IN within the last 30 days too, so
            # baseline sold value there stays small and predictable - the
            # dedicated top-up step (5c) is what actually steers the
            # monthly total toward the target, not this random walk.
            weights = [25, 75] if is_recent else [65, 35]
            t_type = random.choices(
                [TransactionType.STOCK_OUT, TransactionType.STOCK_IN],
                weights=weights,
            )[0]

        prev_stock = current_stock
        out_cap = 5 if is_recent else 50

        if t_type == TransactionType.STOCK_OUT:
            max_out = min(current_stock, out_cap)
            if max_out < 1:
                t_type = TransactionType.STOCK_IN
                qty = random.randint(5, 100)
                new_stock = current_stock + qty
            else:
                qty = random.randint(1, max_out)
                new_stock = current_stock - qty
        else:
            qty = random.randint(5, 100)
            new_stock = current_stock + qty

        current_stock = new_stock

        # ---- Replay sync_stock_alert()'s exact branching ---- #
        if t_type == TransactionType.STOCK_OUT:
            if new_stock == 0:
                target = AlertStatus.CRITICAL
            elif new_stock < reorder_level:
                target = AlertStatus.LOW_STOCK
            else:
                target = None

            if target is not None:
                if active_alert:
                    active_alert["status"] = target
                else:
                    active_alert = {
                        "alert_id": uuid.uuid4(),
                        "item_id": item_id,
                        "supplier_id": supplier_id,
                        "status": target,
                        "created_at": date,
                        "resolved_at": None,
                    }
                    alert_rows.append(active_alert)
        else:  # STOCK_IN
            if active_alert:
                if new_stock >= reorder_level:
                    active_alert["status"] = AlertStatus.RESOLVED
                    active_alert["resolved_at"] = date
                    active_alert = None
                else:
                    active_alert["status"] = AlertStatus.LOW_STOCK

        note = (
            "Stock received from supplier"
            if t_type == TransactionType.STOCK_IN
            else "Stock issued to customer"
        )
        transaction_rows.append(
            dict(
                transaction_id=uuid.uuid4(),
                item_id=item_id,
                user_id=random.choice(transaction_user_ids),
                transaction_type=t_type,
                quantity=qty,
                previous_quantity=prev_stock,
                new_quantity=new_stock,
                transaction_date=date,
                note=note,
            )
        )

    last_date = dates[-1]

    # Always force-resolve any still-open alert here. Items chosen to stay
    # genuinely CRITICAL/LOW_STOCK get that applied afterward by the caller.
    if active_alert:
        resolve_date = min(
            last_date + timedelta(hours=random.randint(1, 48)),
            datetime.now(local_tz),
        )
        if resolve_date <= last_date:
            resolve_date = last_date + timedelta(minutes=1)

        qty = max(reorder_level - current_stock, 0) + random.randint(20, 100)
        new_stock = current_stock + qty

        transaction_rows.append(
            dict(
                transaction_id=uuid.uuid4(),
                item_id=item_id,
                user_id=random.choice(transaction_user_ids),
                transaction_type=TransactionType.STOCK_IN,
                quantity=qty,
                previous_quantity=current_stock,
                new_quantity=new_stock,
                transaction_date=resolve_date,
                note="Stock received from supplier - restock",
            )
        )

        active_alert["status"] = AlertStatus.RESOLVED
        active_alert["resolved_at"] = resolve_date
        current_stock = new_stock
        last_date = resolve_date

    return current_stock, transaction_rows, alert_rows, last_date


def craft_terminal_alert(
    item_id,
    supplier_id,
    reorder_level,
    current_stock,
    last_date,
    target_status,
    transaction_user_ids,
):
    """
    Appends ONE final STOCK_OUT transaction that deliberately drops the item
    into LOW_STOCK or CRITICAL and leaves it there - no resolving transaction
    follows, so the alert stays genuinely active. Matches the example given:
    item at 20, reorder 5, a stock-out to 4 creates LOW_STOCK; if nothing
    stocks it back in, that alert simply stays active.
    """
    if target_status == AlertStatus.CRITICAL:
        final_qty = 0
    else:  # LOW_STOCK
        final_qty = random.randint(1, max(reorder_level - 1, 1))

    qty = current_stock - final_qty
    now_ts = datetime.now(local_tz)
    recent_cutoff = now_ts - timedelta(days=30)
    base_date = last_date if last_date else (now_ts - timedelta(days=60))

    if base_date < recent_cutoff:
        # Keep this event dated BEFORE the last-30-days window so it
        # doesn't affect the monthly sold-value target at all - the alert
        # only needs to still be open today, not have been created today.
        latest_safe = recent_cutoff - timedelta(hours=1)
        earliest = base_date + timedelta(hours=1)
        if earliest >= latest_safe:
            event_date = earliest
        else:
            span_seconds = int((latest_safe - earliest).total_seconds())
            event_date = earliest + timedelta(seconds=random.randint(0, span_seconds))
    else:
        # Item's last real transaction was already within the last 30
        # days - can't date this before it, so it unavoidably falls in
        # the revenue window this one time.
        event_date = min(base_date + timedelta(hours=random.randint(1, 72)), now_ts)
        if event_date <= base_date:
            event_date = base_date + timedelta(minutes=1)

    transaction_row = dict(
        transaction_id=uuid.uuid4(),
        item_id=item_id,
        user_id=random.choice(transaction_user_ids),
        transaction_type=TransactionType.STOCK_OUT,
        quantity=qty,
        previous_quantity=current_stock,
        new_quantity=final_qty,
        transaction_date=event_date,
        note="Stock issued to customer",
    )
    alert_row = dict(
        alert_id=uuid.uuid4(),
        item_id=item_id,
        supplier_id=supplier_id,
        status=target_status,
        created_at=event_date,
        resolved_at=None,
    )
    return final_qty, transaction_row, alert_row


# --------------------------------------------------------------------------- #
# Main seeding routine
# --------------------------------------------------------------------------- #
async def seed_database() -> None:
    async with async_session_maker() as session:

        # ---- Anchor check: only seed if ALL owned tables are empty ---- #
        # Checking just `categories` isn't enough - if someone truncates
        # categories but forgets suppliers/items, this used to pass the
        # check and then crash halfway through on a duplicate key (e.g.
        # supplier1@suppliers.lk already existing). Checking all of them
        # catches that up front with a clear message instead.
        counts = {}
        for label, model in [
            ("categories", Category),
            ("suppliers", Supplier),
            ("items", Item),
        ]:
            result = await session.execute(select(func.count()).select_from(model))
            counts[label] = result.scalar_one()

        if any(c > 0 for c in counts.values()):
            non_empty = ", ".join(f"{k} ({v} rows)" for k, v in counts.items() if v > 0)
            print(
                f"Seed data already present in: {non_empty}. Skipping seeding.\n"
                f"If you want a full reset, truncate ALL of these together first:\n"
                f"  TRUNCATE TABLE stock_alerts, transactions, items, suppliers, "
                f"categories RESTART IDENTITY CASCADE;\n"
                f"  DELETE FROM users;"
            )
            return

        used_phones: set = set()
        used_nics: set = set()
        used_emails: set = set()
        used_supplier_names: set = set()

        # ------------------------------------------------------------- #
        # 1. Users - 10 total: 2 ADMIN (incl. musfir), 1 AUDITOR,
        #    2 INVENTORY_MANAGER, 5 SALES. Only the 2 admins + 2 IMs ever
        #    perform transactions (business rule) - their ids are
        #    collected into transaction_user_ids below.
        #
        #    musfir is checked independently of the categories anchor, so
        #    a partial truncate (categories only) won't crash on restart -
        #    it reuses the existing musfir_id instead of re-inserting it.
        #    The other 9 are only created when the anchor is empty.
        # ------------------------------------------------------------- #
        used_usernames: set = set()

        existing_user = await session.execute(
            select(
                User.user_id,
                User.full_name,
                User.user_name,
                User.role,
                User.created_at,
            ).where(User.user_name == "musfir")
        )
        existing_row = existing_user.one_or_none()

        transaction_user_ids = []  # everyone EXCEPT auditor: admin + IM + sales
        admin_ids = []
        im_ids = []
        sales_ids = []
        all_users_info = []  # for audit log generation below
        user_rows = []

        if existing_row is not None:
            (
                musfir_id,
                musfir_full_name,
                musfir_username,
                musfir_role,
                musfir_created_at,
            ) = existing_row
            print("musfir user already exists - reusing it.")
        else:
            musfir_id = uuid.uuid4()
            musfir_full_name = "Musfir Mohamed"
            musfir_username = "musfir"
            musfir_role = UserRole.ADMIN
            musfir_created_at = random_datetime_last_365_days()
            used_usernames.add("musfir")
            user_rows.append(
                dict(
                    user_id=musfir_id,
                    full_name=musfir_full_name,
                    user_name=musfir_username,
                    nic=gen_nic(used_nics),
                    email=gen_email("musfir", "lankahardware.lk", used_emails),
                    phone=gen_phone(used_phones),
                    password_hash=hash_password(DEFAULT_PASSWORD),
                    role=musfir_role,
                    is_active=True,
                    created_at=musfir_created_at,
                    updated_at=musfir_created_at,
                )
            )

        transaction_user_ids.append(musfir_id)
        admin_ids.append(musfir_id)
        all_users_info.append(
            dict(
                user_id=musfir_id,
                full_name=musfir_full_name,
                user_name=musfir_username,
                role=musfir_role,
                created_at=musfir_created_at,
            )
        )

        # role plan for the other 9 users
        other_roles = (
            [UserRole.ADMIN] * 1
            + [UserRole.INVENTORY_MANAGER] * 2
            + [UserRole.AUDITOR] * 1
            + [UserRole.SALES] * 5
        )
        for role in other_roles:
            uid = uuid.uuid4()
            full_name = gen_full_name()
            username = gen_username(full_name, used_usernames)
            ts = random_datetime_last_365_days()
            user_rows.append(
                dict(
                    user_id=uid,
                    full_name=full_name,
                    user_name=username,
                    nic=gen_nic(used_nics),
                    email=gen_email(username, "lankahardware.lk", used_emails),
                    phone=gen_phone(used_phones),
                    password_hash=hash_password(DEFAULT_PASSWORD),
                    role=role,
                    is_active=True,
                    created_at=ts,
                    updated_at=ts,
                )
            )
            all_users_info.append(
                dict(
                    user_id=uid,
                    full_name=full_name,
                    user_name=username,
                    role=role,
                    created_at=ts,
                )
            )
            if role in (UserRole.ADMIN, UserRole.INVENTORY_MANAGER, UserRole.SALES):
                transaction_user_ids.append(uid)
            if role == UserRole.ADMIN:
                admin_ids.append(uid)
            if role == UserRole.INVENTORY_MANAGER:
                im_ids.append(uid)
            if role == UserRole.SALES:
                sales_ids.append(uid)

        if user_rows:
            await session.execute(insert(User), user_rows)

        print(
            f"Users: {len(user_rows)} created this run "
            f"(transaction-eligible users: {len(transaction_user_ids)} "
            f"= 2 admin + 2 inventory manager + 5 sales; auditor excluded)."
        )

        # ------------------------------------------------------------- #
        # 2. Categories
        # ------------------------------------------------------------- #
        category_rows = []
        category_ids = []
        for name in CATEGORY_NAMES:
            cid = uuid.uuid4()
            category_ids.append((cid, name))
            ts = random_datetime_last_365_days()
            category_rows.append(
                dict(
                    category_id=cid,
                    category_name=name,
                    description=f"Products and supplies related to {name.lower()}.",
                    created_at=ts,
                    updated_at=ts,
                )
            )
        await session.execute(insert(Category), category_rows)

        # ------------------------------------------------------------- #
        # 3. Suppliers (40 total, 7 inactive)
        # ------------------------------------------------------------- #
        inactive_flags = [False] * (NUM_SUPPLIERS - NUM_INACTIVE_SUPPLIERS) + [
            True
        ] * NUM_INACTIVE_SUPPLIERS
        random.shuffle(inactive_flags)

        supplier_rows = []
        suppliers = []  # (supplier_id, is_active)
        for i in range(NUM_SUPPLIERS):
            sid = uuid.uuid4()
            is_inactive = inactive_flags[i]
            ts = random_datetime_last_365_days()
            supplier_rows.append(
                dict(
                    supplier_id=sid,
                    supplier_name=gen_supplier_name(used_supplier_names),
                    contact_person=gen_full_name(),
                    phone=gen_phone(used_phones),
                    email=gen_email(f"supplier{i+1}", "suppliers.lk", used_emails),
                    address=gen_address(),
                    is_active=not is_inactive,
                    created_at=ts,
                    updated_at=ts,
                    notes=random.choice(SUPPLIER_NOTE_TEMPLATES),
                    total_supplies=random.randint(5, 200),
                )
            )
            suppliers.append((sid, not is_inactive))
        await session.execute(insert(Supplier), supplier_rows)

        # ------------------------------------------------------------- #
        # 4. Items (150 total, 22 inactive, always above reorder level)
        #    quantity_in_stock is decided AFTER simulating each item's
        #    transaction + alert history below (step 5), not here.
        # ------------------------------------------------------------- #
        inactive_item_flags = [False] * (NUM_ITEMS - NUM_INACTIVE_ITEMS) + [
            True
        ] * NUM_INACTIVE_ITEMS
        random.shuffle(inactive_item_flags)

        item_base = []  # metadata only, quantity_in_stock filled in later
        used_item_names: set = set()
        sku_counter = 1000

        # Build 6 unique items per category (25 x 6 = 150)
        idx = 0
        for cid, cname in category_ids:
            stems, sizes, unit = CATEGORY_ITEM_TEMPLATES[cname]
            combos = [(s, sz) for s in stems for sz in sizes]  # 3 x 3 = 9 combos
            random.shuffle(combos)
            chosen_combos = combos[:6]

            prefix = "".join(w[0] for w in cname.split() if w.lower() != "and").upper()

            for stem, size in chosen_combos:
                item_id = uuid.uuid4()
                item_name = f"{stem} {size}"
                if item_name in used_item_names:
                    item_name = f"{item_name} {random.randint(1, 999)}"
                used_item_names.add(item_name)

                sku_counter += 1
                sku = f"{prefix}-{sku_counter}"

                supplier_id, supplier_active = random.choice(suppliers)
                is_active = not inactive_item_flags[idx]

                reorder_level = random.randint(10, 50)

                cost_price = (
                    Decimal(random.randint(150, 15000)) / 100 * random.randint(1, 20)
                )
                cost_price = Decimal(str(round(float(cost_price), 2)))
                selling_price = Decimal(
                    str(round(float(cost_price) * random.uniform(1.15, 1.6)))
                ).quantize(Decimal("1.00"))

                ts = random_datetime_last_365_days()
                item_base.append(
                    dict(
                        item_id=item_id,
                        item_name=item_name,
                        sku=sku,
                        description=f"{item_name} - suitable for residential and commercial use.",
                        category_id=cid,
                        supplier_id=supplier_id,
                        unit=unit,
                        cost_price=cost_price,
                        selling_price=selling_price,
                        reorder_level=reorder_level,
                        reorder_quantity=random.randint(20, 100),
                        is_active=is_active,
                        supplier_active=supplier_active,
                        created_at=ts,
                        updated_at=ts,
                    )
                )
                idx += 1

        # ------------------------------------------------------------- #
        # 5. Simulate transaction + alert history per item (~1000 total
        #    transactions), only for items that are active AND whose
        #    supplier is active. Alerts are created/resolved by replaying
        #    the same state machine as sync_stock_alert(). Every
        #    transaction's user_id is one of the 4 admin/IM users.
        # ------------------------------------------------------------- #
        eligible = [m for m in item_base if m["is_active"] and m["supplier_active"]]

        counts_per_item = defaultdict(int)
        for _ in range(TARGET_TRANSACTIONS):
            meta = random.choice(eligible)
            counts_per_item[meta["item_id"]] += 1

        # Make sure every item picked for a terminal alert actually gets at
        # least a handful of transactions to build a believable history on
        # top of.
        for meta in random.sample(eligible, k=min(6, len(eligible))):
            counts_per_item[meta["item_id"]] = max(counts_per_item[meta["item_id"]], 5)

        item_rows = []
        transaction_rows = []
        alert_rows = []
        last_date_by_item = {}
        stock_by_item = {}

        for meta in item_base:
            count = counts_per_item.get(meta["item_id"], 0)
            final_qty, tx_rows, alerts, last_date = simulate_item_history(
                item_id=meta["item_id"],
                supplier_id=meta["supplier_id"],
                reorder_level=meta["reorder_level"],
                count=count,
                transaction_user_ids=transaction_user_ids,
            )
            transaction_rows.extend(tx_rows)
            alert_rows.extend(alerts)
            last_date_by_item[meta["item_id"]] = last_date
            stock_by_item[meta["item_id"]] = final_qty

            item_rows.append(
                dict(
                    item_id=meta["item_id"],
                    item_name=meta["item_name"],
                    sku=meta["sku"],
                    description=meta["description"],
                    category_id=meta["category_id"],
                    supplier_id=meta["supplier_id"],
                    quantity_in_stock=final_qty,
                    unit=meta["unit"],
                    cost_price=meta["cost_price"],
                    selling_price=meta["selling_price"],
                    reorder_level=meta["reorder_level"],
                    reorder_quantity=meta["reorder_quantity"],
                    is_active=meta["is_active"],
                    created_at=meta["created_at"],
                    updated_at=meta["updated_at"],
                )
            )

        # ------------------------------------------------------------- #
        # 5b. Deterministically leave exactly 6 alerts ACTIVE: 4 LOW_STOCK
        #     and 2 CRITICAL. Every other alert generated above already
        #     ended up RESOLVED. Each of these 6 gets one final STOCK_OUT
        #     that creates the alert, with nothing after it to resolve it -
        #     same pattern as your example (20 -> -16 -> LOW_STOCK, and if
        #     no stock-in ever follows, it just stays active).
        # ------------------------------------------------------------- #
        item_rows_by_id = {row["item_id"]: row for row in item_rows}
        recent_cutoff_for_selection = datetime.now(local_tz) - timedelta(days=30)
        # only items with a healthy current buffer make good candidates;
        # prefer ones whose last real transaction is already outside the
        # last-30-days window so their terminal alert doesn't land inside
        # it and skew the monthly sold-value target.
        all_candidates = [
            m for m in eligible if stock_by_item[m["item_id"]] > m["reorder_level"] + 10
        ]
        quiet_candidates = [
            m
            for m in all_candidates
            if not last_date_by_item.get(m["item_id"])
            or last_date_by_item[m["item_id"]] < recent_cutoff_for_selection
        ]
        candidates = quiet_candidates if len(quiet_candidates) >= 6 else all_candidates
        random.shuffle(candidates)
        targets = [AlertStatus.LOW_STOCK] * 4 + [AlertStatus.CRITICAL] * 2
        chosen = candidates[: len(targets)]

        for meta, target_status in zip(chosen, targets):
            item_id = meta["item_id"]
            final_qty, tx_row, alert_row = craft_terminal_alert(
                item_id=item_id,
                supplier_id=meta["supplier_id"],
                reorder_level=meta["reorder_level"],
                current_stock=stock_by_item[item_id],
                last_date=last_date_by_item[item_id],
                target_status=target_status,
                transaction_user_ids=transaction_user_ids,
            )
            transaction_rows.append(tx_row)
            alert_rows.append(alert_row)
            item_rows_by_id[item_id]["quantity_in_stock"] = final_qty

        # ------------------------------------------------------------- #
        # 5c. Top up the last 30 days' STOCK_OUT sold value to ~LKR
        #     1,000,000. Done as ADDITIONAL sale transactions appended to
        #     the tail of each chosen item's timeline (never rewriting
        #     existing transactions), so:
        #       - per-item continuity still holds (new tx's
        #         previous_quantity is exactly that item's current
        #         tracked stock)
        #       - the 6 deliberately open alerts (chosen/targets above)
        #         are left completely untouched
        #       - no item is ever sold below reorder_level + a safety
        #         buffer, so no NEW alerts get accidentally created
        # ------------------------------------------------------------- #
        MONTHLY_SOLD_VALUE_TARGET = Decimal("1000000")
        REORDER_SAFETY_BUFFER = 10
        now_ts = datetime.now(local_tz)
        last_30_days_cutoff = now_ts - timedelta(days=30)

        selling_price_by_item = {
            row["item_id"]: row["selling_price"] for row in item_rows
        }
        reorder_level_by_item = {m["item_id"]: m["reorder_level"] for m in item_base}
        excluded_item_ids = {
            meta["item_id"] for meta in chosen
        }  # the 6 designated alerts

        current_sold_value = sum(
            (Decimal(t["quantity"]) * selling_price_by_item[t["item_id"]])
            for t in transaction_rows
            if t["transaction_type"] == TransactionType.STOCK_OUT
            and t["transaction_date"] >= last_30_days_cutoff
        )
        shortfall = MONTHLY_SOLD_VALUE_TARGET - current_sold_value

        topup_pool = [m for m in eligible if m["item_id"] not in excluded_item_ids]
        topup_count = 0
        guard = 0

        while shortfall > 0 and topup_pool and guard < 3000:
            guard += 1
            meta = random.choice(topup_pool)
            item_id = meta["item_id"]
            price = selling_price_by_item[item_id]
            if price <= 0:
                continue

            reorder_level = reorder_level_by_item[item_id]
            current_stock = stock_by_item[item_id]
            max_sellable = current_stock - reorder_level - REORDER_SAFETY_BUFFER
            if max_sellable < 1:
                continue

            max_qty_by_price = int(shortfall / price) + 1
            qty = max(1, min(max_sellable, max_qty_by_price, 100))
            new_stock = current_stock - qty

            last_dt = last_date_by_item.get(item_id)
            window_start = (
                last_dt
                if (last_dt and last_dt > last_30_days_cutoff)
                else last_30_days_cutoff
            )
            if window_start >= now_ts:
                window_start = now_ts - timedelta(hours=1)
            span_seconds = max(int((now_ts - window_start).total_seconds()), 60)
            event_date = window_start + timedelta(
                seconds=random.randint(0, span_seconds)
            )

            transaction_rows.append(
                dict(
                    transaction_id=uuid.uuid4(),
                    item_id=item_id,
                    user_id=random.choice(transaction_user_ids),
                    transaction_type=TransactionType.STOCK_OUT,
                    quantity=qty,
                    previous_quantity=current_stock,
                    new_quantity=new_stock,
                    transaction_date=event_date,
                    note="Stock issued to customer",
                )
            )

            stock_by_item[item_id] = new_stock
            last_date_by_item[item_id] = event_date
            item_rows_by_id[item_id]["quantity_in_stock"] = new_stock
            shortfall -= Decimal(qty) * price
            topup_count += 1

        achieved_sold_value = MONTHLY_SOLD_VALUE_TARGET - shortfall

        # ------------------------------------------------------------- #
        # 5d. Guarantee every transaction-eligible user (2 admin + 2 IM +
        #     5 sales) has AT LEAST ONE transaction - with ~1000+
        #     transactions across 9 users this is virtually certain
        #     anyway, but this makes it exact rather than probabilistic.
        #     Auditor is never in transaction_user_ids, so never assigned.
        #     Reassigning an existing row's user_id doesn't touch
        #     quantities/dates, so continuity is unaffected.
        # ------------------------------------------------------------- #
        users_with_tx = {t["user_id"] for t in transaction_rows}
        missing_users = [
            uid for uid in transaction_user_ids if uid not in users_with_tx
        ]
        if missing_users and transaction_rows:
            pool_indices = list(range(len(transaction_rows)))
            random.shuffle(pool_indices)
            for uid, idx in zip(missing_users, pool_indices):
                transaction_rows[idx]["user_id"] = uid

        await session.execute(insert(Item), item_rows)

        if alert_rows:
            for batch in chunked(alert_rows, BATCH_SIZE):
                await session.execute(insert(StockAlert), batch)

        for batch in chunked(transaction_rows, BATCH_SIZE):
            await session.execute(insert(Transaction), batch)

        # ------------------------------------------------------------- #
        # 6. Audit logs
        # ------------------------------------------------------------- #
        audit_log_rows = []

        def add_audit(
            user_id,
            action,
            description,
            target_table,
            target_id,
            created_at,
            old_value=None,
            new_value=None,
        ):
            audit_log_rows.append(
                dict(
                    log_id=uuid.uuid4(),
                    user_id=user_id,
                    action=action,
                    description=description,
                    target_table=target_table,
                    target_id=target_id,
                    old_value=old_value,
                    new_value=new_value,
                    created_at=created_at,
                )
            )

        # 6a. Login / logout - ~50 logs across all 10 users, random dates.
        #     target_id stays None here, matching your actual crud
        #     (AuditlogCreate never sets it for login/logout).
        for _ in range(50):
            u = random.choice(all_users_info)
            action = random.choice(
                [AuditAction.LOGIN_SUCCESS, AuditAction.LOGOUT_SUCCESS]
            )
            verb = "logged in" if action == AuditAction.LOGIN_SUCCESS else "logged out"
            add_audit(
                user_id=u["user_id"],
                action=action,
                description=(
                    f"User {u['full_name']} ({u['user_name']}) with role "
                    f"{u['role'].value} {verb} successfully."
                ),
                target_table="users",
                target_id=None,
                created_at=random_datetime_last_365_days(),
            )

        # 6b. User create - one per user, always by musfir, created_at ==
        #     that user's own created_at exactly.
        for u in all_users_info:
            add_audit(
                user_id=musfir_id,
                action=AuditAction.USER_CREATE,
                description=(
                    f"Created user {u['full_name']} ({u['user_name']}) "
                    f"with role {u['role'].value}."
                ),
                target_table="users",
                target_id=u["user_id"],
                created_at=u["created_at"],
            )

        # 6c. Category create - one per category, exact created_at,
        #     creator = 2 admins + 1 IM pool.
        for row in category_rows:
            add_audit(
                user_id=pick_admin_or_im_creator(admin_ids, im_ids),
                action=AuditAction.CATEGORY_CREATE,
                description=f"Created category '{row['category_name']}'.",
                target_table="categories",
                target_id=row["category_id"],
                created_at=row["created_at"],
            )

        # 6d. Supplier create - same rule as categories.
        for row in supplier_rows:
            add_audit(
                user_id=pick_admin_or_im_creator(admin_ids, im_ids),
                action=AuditAction.SUPPLIER_CREATE,
                description=f"Created supplier '{row['supplier_name']}'.",
                target_table="suppliers",
                target_id=row["supplier_id"],
                created_at=row["created_at"],
            )

        # 6e. Supplier deactivate - only the inactive suppliers, always by
        #     musfir, dated after that supplier's created_at.
        for row in supplier_rows:
            if not row["is_active"]:
                deact_time = min(
                    row["created_at"]
                    + timedelta(
                        days=random.randint(1, 60), hours=random.randint(0, 23)
                    ),
                    datetime.now(local_tz),
                )
                add_audit(
                    user_id=musfir_id,
                    action=AuditAction.SUPPLIER_DEACTIVATE,
                    description=f"Deactivated supplier '{row['supplier_name']}'.",
                    target_table="suppliers",
                    target_id=row["supplier_id"],
                    created_at=deact_time,
                )

        # 6f. Item create - same rule as categories/suppliers.
        for row in item_rows:
            add_audit(
                user_id=pick_admin_or_im_creator(admin_ids, im_ids),
                action=AuditAction.ITEM_CREATE,
                description=f"Created item '{row['item_name']}' (SKU {row['sku']}).",
                target_table="items",
                target_id=row["item_id"],
                created_at=row["created_at"],
            )

        # 6g. Item deactivate - only the inactive items, always by musfir,
        #     dated after that item's created_at.
        for row in item_rows:
            if not row["is_active"]:
                deact_time = min(
                    row["created_at"]
                    + timedelta(
                        days=random.randint(1, 60), hours=random.randint(0, 23)
                    ),
                    datetime.now(local_tz),
                )
                add_audit(
                    user_id=musfir_id,
                    action=AuditAction.ITEM_DEACTIVATE,
                    description=f"Deactivated item '{row['item_name']}'.",
                    target_table="items",
                    target_id=row["item_id"],
                    created_at=deact_time,
                )

        # 6h. Item price update - 20 random items, NO actual price change
        #     in the items table. new_value is set to that item's real
        #     current cost_price; old_value is a fabricated prior price
        #     (+/-15%) purely for the log entry.
        price_change_items = random.sample(item_rows, k=min(20, len(item_rows)))
        for row in price_change_items:
            current_cost = row["cost_price"]
            variation = Decimal(str(round(random.uniform(0.85, 1.15), 2)))
            old_cost = (current_cost * variation).quantize(Decimal("0.01"))
            if old_cost == current_cost:
                old_cost = current_cost + Decimal("1.00")
            log_time = min(
                row["created_at"] + timedelta(days=random.randint(1, 300)),
                datetime.now(local_tz),
            )
            add_audit(
                user_id=pick_admin_or_im_creator(admin_ids, im_ids),
                action=AuditAction.ITEM_PRICE_UPDATE,
                description=(
                    f"Updated cost price of item '{row['item_name']}' "
                    f"from LKR {old_cost} to LKR {current_cost}."
                ),
                target_table="items",
                target_id=row["item_id"],
                created_at=log_time,
                old_value=str(old_cost),
                new_value=str(current_cost),
            )

        for batch in chunked(audit_log_rows, BATCH_SIZE):
            await session.execute(insert(AuditLog), batch)

        await session.commit()

        critical_count = sum(
            1 for a in alert_rows if a["status"] == AlertStatus.CRITICAL
        )
        low_stock_count = sum(
            1 for a in alert_rows if a["status"] == AlertStatus.LOW_STOCK
        )
        resolved_count = sum(
            1 for a in alert_rows if a["status"] == AlertStatus.RESOLVED
        )
        tx_by_user = defaultdict(int)
        for t in transaction_rows:
            tx_by_user[t["user_id"]] += 1
        print(
            f"Seed complete: {len(user_rows)} new users, {len(category_rows)} categories, "
            f"{len(supplier_rows)} suppliers, {len(item_rows)} items, "
            f"{len(transaction_rows)} transactions across {len(tx_by_user)} users, "
            f"{len(alert_rows)} alerts total "
            f"({critical_count} active critical, {low_stock_count} active low stock, "
            f"{resolved_count} resolved). "
            f"Last 30 days sold value: LKR {achieved_sold_value:,.2f} "
            f"(target 1,000,000; {topup_count} top-up sale transactions added). "
            f"{len(audit_log_rows)} audit log entries created."
        )


if __name__ == "__main__":
    import asyncio

    asyncio.run(seed_database())
